# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91549b96bd16a051117f736eaf31c5c7067a4a8be18ae0da1336bf331966d80d9362462705d3658e273dc709f61cb3c079e8bfd53aa5876d4c9aca3c3ee4a847

test:
  secret_key_base: 255486b45ff60afb2726f6950ca2bbbfa37c95ef4263d54d2cf3b0a1fd45b77755b70cb17e155c5d22b00a9adeda06dea4e5195e00b5433d212b6c3a383f9f21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
